name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    if: github.event.repository.fork == false

    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: arm64-darwin
          - os: macos-latest
            platform: x86_64-darwin
          - os: ubuntu-latest
            platform: ruby
          - os: ubuntu-latest
            platform: aarch64-linux-android
          - os: ubuntu-latest
            platform: arm-linux-androideabi
          - os: ubuntu-latest
            platform: riscv64-linux-android
          - os: ubuntu-latest
            platform: x86_64-linux-android
          - os: ubuntu-latest
            platform: aarch64-linux-gnu
          - os: ubuntu-latest
            platform: arm-linux-gnueabihf
          - os: ubuntu-latest
            platform: riscv64-linux-gnu
          - os: ubuntu-latest
            platform: x86_64-linux-gnu
          - os: ubuntu-latest
            platform: aarch64-linux-musl
          - os: ubuntu-latest
            platform: arm-linux-musleabihf
          - os: ubuntu-latest
            platform: riscv64-linux-musl
          - os: ubuntu-latest
            platform: x86_64-linux-musl
          - os: windows-latest
            platform: aarch64-mingw-ucrt
          - os: windows-latest
            platform: x64-mingw-ucrt

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          rubygems: latest
          bundler-cache: true

      # TODO: remove after https://github.com/sass/dart-sass/pull/2413
      - name: Build dart-sass
        if: matrix.platform == 'ruby'
        uses: ./.github/actions/build-dart-sass

      - name: Compile
        run: bundle exec rake compile ext_platform=${{ matrix.platform }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Build
        run: rake -f -r bundler/gem_tasks build gem_platform=${{ matrix.platform }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: pkg/*.gem

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: pkg-${{ matrix.platform }}
          path: pkg/*.gem
          if-no-files-found: error
          compression-level: 0

  release:

    if: github.event.repository.fork == false

    needs: [build]

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          rubygems: latest

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          pattern: pkg-*
          merge-multiple: true

      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0

      - name: Release
        run: find . -name '*.gem' -print0 | sort -rz | xargs -0 -n 1 -- gem push
