name: schedule

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  spec:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
        ruby-version:
          - ruby-head
          - jruby-head
          - truffleruby-head
          - truffleruby+graalvm-head
        exclude:
          - os: windows-latest
            ruby-version: truffleruby-head
          - os: windows-latest
            ruby-version: truffleruby+graalvm-head
          - os: windows-11-arm
            ruby-version: truffleruby-head
          - os: windows-11-arm
            ruby-version: truffleruby+graalvm-head

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup java
        if: matrix.ruby-version == 'jruby-head'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Compile
        run: bundle exec rake compile
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Spec
        run: bundle exec rake spec

      - name: Install
        run: rake -f -r bundler/gem_tasks install
